# baseURL = "https://camera.dog/"
languageCode = "en"
defaultContentLanguage = "en"

# title = "Luke Spots"
copyright = "Copyright Luke Spots - BARK BARK BARK"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Luke Spots"
  headline = "A SoCal based furry photographer and business owner"
  image = "author.jpg"  # path relative to static directory

  links = [
    { email = "mailto:luke@lukespots.com" },
    { link = "https://lukespots.com/" },
    { bluesky = "https://bsky.app/profile/lukespots.bsky.social" },
    # { discord = "https://discord.gg/invitecode" },
    { instagram = "https://instagram.com/luke_spots" },
    # { patreon = "https://www.patreon.com/username" },
    { reddit = "https://reddit.com/user/luwuke" },
    { telegram = "https://t.me/luke_spots" },
    # { threads = "https://threads.com/luke_spots" },
    { tiktok = "https://tiktok.com/@luke_spots" },
    { twitter = "https://twitter.com/luke_spots" },
    { youtube = "https://www.youtube.com/@luke_spots" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
